---
apiVersion: v1
kind: Service
metadata:
  name: capeerorg1
  labels:
    app: capeerorg1
spec:
  type: NodePort
  selector:
    app: capeerorg1
  ports:
  - protocol: TCP
    port: 7054
    nodePort: 31001
    name: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: capeerorg1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capeerorg1
  template:
    metadata:
      labels:
        app: capeerorg1
    spec:
      volumes:
      - name: shared
        hostPath:
          path: /tmp
#      volumes:
#      - name: shared
#        persistentVolumeClaim:
#          claimName: shared

      containers:
      - name: capeerorg1
        image: hyperledger/fabric-ca:x86_64-1.0.5
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
        env:
        - name: FABRIC_CA_SERVER_CA_CERTFILE
          value: /shared/crypto-config/peerOrganizations/peerorg1/ca/ca.peerorg1-cert.pem
        - name: FABRIC_CA_SERVER_CA_KEYFILE
          value: /shared/crypto-config/peerOrganizations/peerorg1/ca/key.pem
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca-peerorg1
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /shared/crypto-config/peerOrganizations/peerorg1/ca/ca.peerorg1-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /shared/crypto-config/peerOrganizations/peerorg1/ca/key.pem
        volumeMounts:
        - mountPath: /shared
          name: shared
      initContainers:
      - name: init-capeerorg1
        image: marshall628/kubernetes_fabric_utils:x86_64-1.0.5
        command: ["sh", "-c", "sleep 1 && while [ ! -f /shared/bootstrapped ]; do echo Waiting for bootstrap; sleep 1; done;"]
        volumeMounts:
        - mountPath: /shared
          name: shared

